# Generated by Django 4.0.6 on 2022-07-29 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentforseller',
            name='buyer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments_from_buyers_to_seller', to='flowers.buyer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commentsforlots',
            name='buyer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments_from_buyers_to_lots', to='flowers.buyer'),
            preserve_default=False,
        ),
    ]
