# Generated by Django 4.0.6 on 2022-07-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0002_commentforseller_buyer_commentsforlots_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deal',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
