# Generated by Django 4.0.6 on 2022-07-29 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flowers', '0003_deal_count_deal_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='seller',
        ),
        migrations.CreateModel(
            name='TypeOfUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Seller', 'Seller'), ('Buyer', 'Buyer')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='commentforseller',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_from_buyers_to_seller', to='flowers.typeofuser'),
        ),
        migrations.AlterField(
            model_name='commentforseller',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_to_seller', to='flowers.typeofuser'),
        ),
        migrations.AlterField(
            model_name='commentsforlots',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_from_buyers_to_lots', to='flowers.typeofuser'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_with_buyer', to='flowers.typeofuser'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_with_seller', to='flowers.typeofuser'),
        ),
        migrations.AlterField(
            model_name='flowerlot',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flower_lot_of_seller', to='flowers.typeofuser'),
        ),
        migrations.DeleteModel(
            name='Buyer',
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
