# Generated by Django 4.0.6 on 2022-07-29 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flowers', '0004_remove_seller_seller_typeofuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='commentforseller',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_from_buyers_to_seller', to='flowers.buyer'),
        ),
        migrations.AlterField(
            model_name='commentforseller',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_to_seller', to='flowers.seller'),
        ),
        migrations.AlterField(
            model_name='commentsforlots',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_from_buyers_to_lots', to='flowers.buyer'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_with_buyer', to='flowers.buyer'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_with_seller', to='flowers.seller'),
        ),
        migrations.AlterField(
            model_name='flowerlot',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flower_lot_of_seller', to='flowers.seller'),
        ),
        migrations.DeleteModel(
            name='TypeOfUser',
        ),
    ]
