# Generated by Django 4.0.6 on 2022-07-29 15:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0005_seller_buyer_alter_commentforseller_buyer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='price',
        ),
        migrations.AlterField(
            model_name='deal',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flowerlot',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flowerlot',
            name='price',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
