# Generated by Django 4.0.6 on 2022-07-30 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0006_remove_deal_price_alter_deal_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='buyer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='seller',
            name='seller',
            field=models.CharField(max_length=100),
        ),
    ]
