# Generated by Django 4.0.6 on 2022-07-30 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0008_alter_buyer_buyer_alter_seller_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='buyer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='seller',
            name='seller',
            field=models.CharField(max_length=100),
        ),
    ]
