# Generated by Django 4.0.6 on 2022-07-30 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flowers', '0015_alter_buyer_is_buyers_alter_seller_is_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='is_buyers',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='is_seller',
        ),
        migrations.CreateModel(
            name='TypeOfUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_seller', models.BooleanField()),
                ('is_buyers', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='buyer',
            name='buyer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flowers.typeofuser'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='seller',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flowers.typeofuser'),
        ),
    ]
